directories:
  output: release
  buildResources: build
appId: com.reportcard.app
productName: Report Card Management System
files:
  - filter:
      - dist/**/*
      - electron/**/*
extraResources:
  - from: staging/backend
    to: backend
  - from: jre
    to: jre
win:
  target: nsis
electronVersion: 43.1.0
